# Generated by Django 6.0 on 2025-12-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewset_spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canciones',
            name='artistname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='discos',
            name='artistname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
