# Generated by Django 6.0 on 2025-12-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewset_spotify', '0002_canciones_artistname_discos_artistname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canciones',
            name='artistname',
            field=models.CharField(default='Desconocido', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discos',
            name='artistname',
            field=models.CharField(default='Desconocido', max_length=150),
            preserve_default=False,
        ),
    ]
