# Generated by Django 6.0 on 2025-12-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewset_spotify', '0003_alter_canciones_artistname_alter_discos_artistname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discos',
            old_name='discotitle',
            new_name='albumname',
        ),
    ]
